### ISSUE TITLE
Is it possible to show the current folder in front of cursor on the current line?

### ISSUE THREAD

**Issue by kirkouimet** [bliker/cmder#338]
Is it possible to mimic the standard cmd.exe behavior by keeping the cursor on the same line as the current folder, e.g.,

C:\Folder _

![capture](https://cloud.githubusercontent.com/assets/62191/5259357/dc46930e-79b3-11e4-8a3d-dccdd38f6750.PNG)

**Comment by fredericseiler** [comment]
You can change the prompt style in your cmder\vendor\init.bat.

![image](https://cloud.githubusercontent.com/assets/954168/5765820/dcfc92c8-9cfc-11e4-8d38-6672d6d031ca.png)

- If you want the default Windows cmd prompt, just replace it with `@prompt $P$G`.
- If you want to keep the "advanced" Cmder prompt, but without the line break, remove the `$S$_` part.

![image](https://cloud.githubusercontent.com/assets/954168/5765915/bee90e50-9cfd-11e4-8d89-381673153504.png)

**Comment by kirkouimet** [comment]
Thanks!

**Comment by miparnisari** [comment]
Where is that line in the latest version? I cannot find it :(

**Comment by fredericseiler** [comment]
Starting from Cmder 1.3.0, you will find the prompt definition in `vendor\clink.lua` (function `set_prompt_filter()`) if you're using a cmd task, or in `vendor\profile.ps1` (function `global:prompt`) if you're using a PowerShell task.

If you want to properly override the prompt in a cmd task, just add your own prompt.lua in the `config` folder with this definition :
```lua
function my_prompt_filter()
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;40m{cwd} {git}{hg} \n\x1b[1;30;40m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "λ")
end

clink.prompt.register_filter(my_prompt_filter, 1)
```
You can then customize the prompt without loosing it when updating Cmder.

**Comment by riOwnage** [comment]
Working with cmder, prompt.lua in config or vendor folder doesn't work unfortunatly.
when i delete the section `function my_prompt_filter()` till `end` and add what @fredericseiler said (whole section of `function my_prompt_filter()` i get this:

![capture](https://user-images.githubusercontent.com/38831452/39618755-770447e2-4f85-11e8-9d13-cf8db3ead255.PNG)

please help

**Comment by jalovatt** [comment]
New user, not familiar with terminal stuff at all other than some mandatory DOS usage to play games under Windows 3.1 when I was a kid.

Like the OP, I'm used to a single-line prompt, so I tried the Lua example above. It worked, but it also removed all text coloring from the terminal. So I deleted the .lua file, but the coloring hasn't come back. I tried putting the file back and fiddling with the prompt it defines, but nothing I do makes a difference. Likewise,  editing _init.bat_ doesn't seem to do anything.

How do I fix this and/or get what I was originally aiming for - single-line prompt with coloring?

I'm sure the problem here is one of those between-keyboard-and-chair deals. Cheers.

**Comment by daxgames** [comment]
@noxasch Not a good solution as it will be overwritten on update.  Instead add the below to a file called `%cmder_root%\config\my_prompt.lua`:

```
function my_prompt_filter()
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;40m{cwd}{git}{hg}{svn}\x1b[1;30;40m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "λ")
end

clink.prompt.register_filter(my_prompt_filter, 1)
```

**Comment by gabrielfsousa** [comment]
i'm trying to change the prompt on Version 1.3.11.843, like @noxasch and @daxgames but theres no change.... what i'm doing wrong ?

**Comment by Kotsuha** [comment]
The above `my_prompt_filter()` approach is great and I've successfully changed the "λ" symbol. However it makes non-ASCII path characters garbled because 

> clink.get_cwd() is returning a string which is differently encoded than what
clink.prompt.value expects.

as mentioned in https://github.com/cmderdev/cmder/pull/1070. 

If I `cd` to a non-ASCII path it looks like this

```
D:\PortableApps\Cmder (master)
★ cd "D:\Temp\あいうえお"

D:\Temp\?????
★
```

How can I solve this? I've looked into the `%cmder_root%\vendor\clink.lua` file (not familiar with Lua though) and figured maybe I need to cache the original `cwd`. But if modification to original file is needed then the benefit of creating a new file is gone.

Cmder Version 1.3.14.982
