### ISSUE TITLE
Bad unicode support (wrong glyphs on alsamixer)

### ISSUE THREAD

**Issue by rfgamaral** [bliker/cmder#545]
They say a picture is worth a thousand words:

![alsamixer_consoles](https://cloud.githubusercontent.com/assets/96476/8508433/2f0ea484-2268-11e5-8a71-bb9944fcb8c4.png)

- **Top-left:** Cmder (cmd.exe)
- **Bottom-left:** Cmder (cmd.exe real console)
- **Top-right:** Cygwin Mintty
- **Bottom-right:** cmd.exe

Only Cmder, for some strange reason, does not have proper glyph support for alsamixer (not sure if it's relevant but I'm accessing my Debian Wheezy machine through SSH).

I've read the [Unicode Support](http://conemu.github.io/en/UnicodeSupport.html) page from ConEmu and I still can't get this to work properly. The `chcp 65001` command doesn't help. And when I run `chcp` on `cmd.exe` to check the codepage, it reports 850, same as Cmder, so it should just work.

I'm using the same font on all consoles and that is `Consolas` with font charset `ANSI` and I've also tried to change the alternative font for pseudographics, nothing works.

This happens only on the following Cmder task: `cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%USERPROFILE%`. After messing with `init.bat` contents I've found that removing `%GIT_INSTALL_ROOT%\bin;` from https://github.com/bliker/cmder/blob/master/vendor/init.bat#L41, "solves" the problem. Glyphs are now properly rendered for alsamixer.

But this is not a solution because it prevents me from using all the msysGit tools inside Cmder.

Thoughts on how to properly solve this?

**Comment by Maximus5** [comment]
What ssh do you run in the bottom-right cmd.exe? Use taskmanager or ProcessExplorer to find exact/full path to the ssh.exe file in all cases. I believe that are different. So, to fix the problem you have to set up your %PATH% to point the directory with prop proper shh first.
But where it is? cygwin? Why not to install git package there instead of using msysgit?
Another option is to compare profiles of cygwin (where you have proper ssh?) and msysgit. And there is already newer version - git-for-windows v2.x.

**Comment by rfgamaral** [comment]
Yes, they are different. Mintty and cmd.exe are both using the version from Cygwin. But Cmder is using the one from the Git for Windows package.

>Why not to install git package there instead of using msysgit?

I thought they are were exactly the same, just renamed ("msysGit" to "Git for Windows").

>Another option is to compare profiles of cygwin (where you have proper ssh?) and msysgit.

What do you mean with profiles?

>And there is already newer version - git-for-windows v2.x.

The [official website](https://msysgit.github.io/) states 1.9.5 as the latest stable version. I didn't know about that one until you mentioned it. I guess I can download it from [here](https://github.com/git-for-windows/git/releases). We'll need to try this new version.

**Comment by Maximus5** [comment]
> I thought they were exactly the same, just renamed ("msysGit" to "Git for Windows").

I mean cygwin has git package, but AFAIK it used cygwin core. So it is different from "msysGit".

![2015-07-05_23-14-27](https://cloud.githubusercontent.com/assets/1222388/8513267/a703a062-236b-11e5-9c79-f5fa4e9fd419.png)

> What do you mean with profiles?

.bashrc and, actually, dozens of other configuration files. Of course they msys and cygwin has different configs even if you use same `$home`.

> from [here](https://github.com/git-for-windows/git/releases).

Exactly. Not sure about its production stage, but I'm using this updated version in my work because do not like cygwin.

**Comment by rfgamaral** [comment]
I started using that version too. Well, they say it's an RC4, they should be close to release a production ready version.

However, since I've installed that version, all my utilities are coming from Cygwin because I only added `git.exe` to the Windows PATH and not everything else (personal choice). My Cmder task is using their custom `init.bat` which is looking for utilities under `Program Files\Git\bin` but on this version they are stored at `Program Files\Git\usr\bin`, and since Cygwin is on Windows path, it falls back to those.

But I tested `ssh.exe` from this Git version and it worked in the same way as `ssh.exe` from Cygwin, the borders on `alsamixer` are now properly rendered. `grep` also has support for color, which it didn't on the previous version.

For now, this works for me. I'm not getting rid of Cygwin just yet for SSH purposes, I still prefer to use Mintty over Cmder/ConEmu (as you are aware from the other issue).
